//! gRPC client that implements `SmtBackend` by calling a remote
//! `soter.v1.SoterSolver/Check`. Used by marquee-apps in production
//! (the `remote-smt` feature on the consuming crate).
//!
//! Per spec §5.3 and §9. Retry policy at the call site:
//! - `ResourceExhausted` → exp backoff, max 3
//! - `DeadlineExceeded`  → no retry; propagate
//! - `Unavailable`       → exp backoff, max 3
//! - `Internal`          → no retry; propagate
//!
//! Hard rule: this backend never silently falls back to a local solver. If the
//! remote call fails the caller (e.g. quorum-sense in M3) decides degradation
//! — typically "skip registration of this evidence", not "fabricate an answer".

use std::time::Duration;

use async_trait::async_trait;
use converge_pack::{ExecutionIdentity, ExecutionProducerIdentity, NativeExecutionIdentity};
use tonic::metadata::MetadataValue;
use tonic::transport::Channel;
use tonic::Request;
use uuid::Uuid;

use crate::backend::SmtBackend;
use crate::types::{SmtError, SmtQuery, SmtReport, SmtStatus, smt_runtime_config};

// Generated by `tonic-prost-build` (build.rs) when `CARGO_FEATURE_REMOTE` is on.
#[allow(
    clippy::doc_markdown,
    clippy::default_trait_access,
    clippy::too_many_lines,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    clippy::trivially_copy_pass_by_ref
)]
pub(crate) mod proto {
    tonic::include_proto!("soter.v1");
}

use proto::soter_solver_client::SoterSolverClient;
use proto::{
    CheckRequest as PbCheckRequest, SmtQuery as PbSmtQuery, SmtReport as PbSmtReport,
    SmtStatusCode, SolverIdentity as PbSolverIdentity,
};

/// Default per-call wallclock budget on the client side. Generous relative to
/// the server's own `timeout_ms` so the server-side SMT timeout fires first
/// and we get a typed `SMT_STATUS_TIMEOUT` rather than a `DeadlineExceeded`
/// gRPC error.
const DEFAULT_CALL_TIMEOUT_SECS: u64 = 60;
const DEFAULT_CONNECT_TIMEOUT_SECS: u64 = 5;

/// gRPC-backed `SmtBackend`.
///
/// One instance per (server, tenant) pair. Cheap to clone — wraps a
/// `tonic::transport::Channel` which is itself an `Arc` internally.
#[derive(Clone)]
pub struct RemoteSmtBackend {
    client: SoterSolverClient<Channel>,
    tenant_app: String,
}

impl std::fmt::Debug for RemoteSmtBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // The tonic `SoterSolverClient` does not implement `Debug` and printing
        // its internal channel handle would be noise; tenant_app is the only
        // identifying field worth showing.
        f.debug_struct("RemoteSmtBackend")
            .field("tenant_app", &self.tenant_app)
            .finish_non_exhaustive()
    }
}

impl RemoteSmtBackend {
    /// Connect to a running soter-server.
    ///
    /// `server_url` accepts:
    /// - `https://soter-server-<hash>-ew.a.run.app` (Cloud Run; tonic auto-negotiates TLS + h2)
    /// - `http://localhost:50052` (local compose; plaintext h2c)
    ///
    /// The constructor blocks until the TCP connect + h2 preface succeed (or
    /// the 5s connect timeout fires). Calls go through the same `Channel`
    /// afterwards; tonic handles reconnects internally.
    ///
    /// # Errors
    /// Returns a `tonic::transport::Error` if the URL is malformed, DNS
    /// fails, the TCP connect fails, or the h2 preface times out.
    pub async fn new(
        server_url: &str,
        tenant_app: &str,
    ) -> Result<Self, tonic::transport::Error> {
        let endpoint = tonic::transport::Endpoint::from_shared(server_url.to_string())?
            .timeout(Duration::from_secs(DEFAULT_CALL_TIMEOUT_SECS))
            .connect_timeout(Duration::from_secs(DEFAULT_CONNECT_TIMEOUT_SECS));
        let channel = endpoint.connect().await?;
        Ok(Self {
            client: SoterSolverClient::new(channel),
            tenant_app: tenant_app.to_string(),
        })
    }

    /// Wrap a payload in a `tonic::Request` with the metadata our server-side
    /// interceptor requires: `x-converge-app` (tenant slug) + a freshly minted
    /// `x-request-id` for log correlation across the client/server boundary.
    fn with_metadata<T>(&self, msg: T) -> Request<T> {
        let mut req = Request::new(msg);
        // Tenant slugs are validated upstream in the TenantRegistry; they are
        // always ASCII. The `expect` would only fire on programmer error
        // (caller passing an invalid slug into `new`) — that is an invariant
        // violation, not a runtime condition we recover from.
        let tenant_value: MetadataValue<_> = self
            .tenant_app
            .parse()
            .expect("tenant slug must be ASCII metadata-safe");
        req.metadata_mut().insert("x-converge-app", tenant_value);
        let request_id: MetadataValue<_> = Uuid::new_v4()
            .to_string()
            .parse()
            .expect("uuid v4 is always ASCII");
        req.metadata_mut().insert("x-request-id", request_id);
        req
    }
}

#[async_trait]
impl SmtBackend for RemoteSmtBackend {
    fn name(&self) -> &'static str {
        "remote-cvc5"
    }

    async fn solve(&self, query: &SmtQuery) -> Result<SmtReport, SmtError> {
        // Validate locally before paying for an RPC. The server validates again
        // (defense in depth) but we save a round trip on obviously-broken
        // queries.
        query.validate()?;

        let pb_query = PbSmtQuery {
            query_id: query.query_id.clone(),
            smtlib: query.smtlib.clone(),
            timeout_ms: query.timeout_ms,
            produce_model: query.produce_model,
            produce_unsat_core: query.produce_unsat_core,
        };
        let request = self.with_metadata(PbCheckRequest {
            query: Some(pb_query),
        });

        let response = self
            .client
            .clone()
            .check(request)
            .await
            .map_err(|status| {
                SmtError::Backend(format!("grpc {}: {}", status.code(), status.message()))
            })?;

        let pb_report = response.into_inner();
        Ok(map_report(query, pb_report))
    }
}

/// Translate the wire `SmtReport` back into the canonical `soter::SmtReport`,
/// reconstructing the `ExecutionIdentity` from the server's `SolverIdentity`
/// message.
///
/// This is the inverse of `soter-server::convert::smt_report_to_proto`. The
/// server flattens `ExecutionIdentity` into `SolverIdentity` for the wire
/// (dropping `build_identity` and `runtime_config` since they are recoverable
/// from the query + server build); we reconstruct on the client side, pulling
/// `runtime_config` from the original query so the audit trail stays
/// reproducible.
fn map_report(query: &SmtQuery, pb_report: PbSmtReport) -> SmtReport {
    let status = match SmtStatusCode::try_from(pb_report.status)
        .unwrap_or(SmtStatusCode::SmtStatusUnspecified)
    {
        SmtStatusCode::SmtStatusSat => SmtStatus::Sat,
        SmtStatusCode::SmtStatusUnsat => SmtStatus::Unsat,
        SmtStatusCode::SmtStatusUnknown | SmtStatusCode::SmtStatusUnspecified => SmtStatus::Unknown,
        SmtStatusCode::SmtStatusTimeout => SmtStatus::Timeout,
        SmtStatusCode::SmtStatusError => SmtStatus::Error,
    };

    let execution_identity = execution_identity_from_proto(query, pb_report.solver_identity);

    let mut report =
        SmtReport::new_with_execution_identity(query, execution_identity, status);
    if let Some(model) = pb_report.model {
        report = report.with_model(model);
    }
    if let Some(unsat_core) = pb_report.unsat_core {
        report = report.with_unsat_core(unsat_core);
    }
    if let Some(diagnostics) = pb_report.diagnostics {
        report = report.with_diagnostics(diagnostics);
    }
    report
}

/// Rebuild a full `ExecutionIdentity` from the wire `SolverIdentity` plus the
/// original `SmtQuery` (for `runtime_config`).
///
/// `build_identity` is reported as `"remote"` — the server's actual build
/// identity is not on the wire today, and a marquee-app's audit log already
/// records that this came over the network via `producer.name = "remote-cvc5"`.
/// `runtime_config` round-trips through `smt_runtime_config` so identity
/// records remain replay-from-audit shaped exactly like a local
/// `Cvc5FfiBackend` answer would have produced.
///
/// If the server omits `solver_identity` (it shouldn't — `convert.rs` always
/// fills it — but the proto field is technically optional) we fall back to
/// `ExecutionIdentity::non_native` so we never construct an invalid identity.
fn execution_identity_from_proto(
    query: &SmtQuery,
    solver_identity: Option<PbSolverIdentity>,
) -> ExecutionIdentity {
    let Some(si) = solver_identity else {
        return ExecutionIdentity::non_native(
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
            "remote-cvc5",
            smt_runtime_config(query),
        );
    };

    let producer = if si.rust_crate.is_empty() {
        ExecutionProducerIdentity::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"))
    } else {
        ExecutionProducerIdentity::new(si.rust_crate, si.rust_crate_version)
    };

    let backend = if si.solver.is_empty() {
        "remote-cvc5".to_string()
    } else {
        si.solver
    };

    // The native identity is only populated when the server reports a native
    // backend (cvc5 today). For non-FFI server backends (hypothetical future:
    // a pure-Rust SMT engine) the server can leave `native_backend` empty and
    // we drop the native_identity slot — `ExecutionIdentity` accepts None.
    let native_identity = if si.native_backend.is_empty() {
        None
    } else {
        Some(NativeExecutionIdentity::new(
            si.native_backend,
            si.native_version.clone(),
            // `source_url` / commits are not on the wire today. Use sentinel
            // values that pass `validate_non_empty` but are obviously
            // remote-attested rather than locally-verified.
            "remote-attested",
            "remote-attested",
            "remote-attested",
            "remote-attested",
        ))
    };

    let backend_version = if si.native_version.is_empty() {
        "remote".to_string()
    } else {
        si.native_version
    };

    ExecutionIdentity::new(
        producer,
        backend,
        backend_version,
        "remote",
        smt_runtime_config(query),
        native_identity,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn proto_solver_identity() -> PbSolverIdentity {
        PbSolverIdentity {
            solver: "cvc5".to_string(),
            native_backend: "CVC5".to_string(),
            native_version: "1.2.0".to_string(),
            rust_crate: "converge-soter-smt".to_string(),
            rust_crate_version: "0.2.3".to_string(),
        }
    }

    #[test]
    fn map_report_preserves_query_id_and_hash() {
        let query = SmtQuery::new("q1", "(check-sat)");
        let pb_report = PbSmtReport {
            query_id: query.query_id.clone(),
            query_hash: query.query_hash(),
            status: SmtStatusCode::SmtStatusSat as i32,
            solver_identity: Some(proto_solver_identity()),
            model: Some("(model)".to_string()),
            unsat_core: None,
            diagnostics: None,
            wall_time_seconds: 0.01,
        };

        let report = map_report(&query, pb_report);

        assert_eq!(report.query_id, "q1");
        assert_eq!(report.query_hash, query.query_hash());
        assert_eq!(report.status, SmtStatus::Sat);
        assert_eq!(report.model.as_deref(), Some("(model)"));
        assert_eq!(report.execution_identity.backend, "cvc5");
        assert!(report.execution_identity.native_identity.is_some());
    }

    #[test]
    fn map_report_decodes_all_status_codes() {
        let query = SmtQuery::new("q1", "(check-sat)");
        for (code, expected) in [
            (SmtStatusCode::SmtStatusSat, SmtStatus::Sat),
            (SmtStatusCode::SmtStatusUnsat, SmtStatus::Unsat),
            (SmtStatusCode::SmtStatusUnknown, SmtStatus::Unknown),
            (SmtStatusCode::SmtStatusTimeout, SmtStatus::Timeout),
            (SmtStatusCode::SmtStatusError, SmtStatus::Error),
            (SmtStatusCode::SmtStatusUnspecified, SmtStatus::Unknown),
        ] {
            let pb_report = PbSmtReport {
                query_id: query.query_id.clone(),
                query_hash: query.query_hash(),
                status: code as i32,
                solver_identity: Some(proto_solver_identity()),
                model: None,
                unsat_core: None,
                diagnostics: None,
                wall_time_seconds: 0.0,
            };
            let report = map_report(&query, pb_report);
            assert_eq!(report.status, expected, "status code {code:?}");
        }
    }

    #[test]
    fn map_report_falls_back_when_solver_identity_missing() {
        let query = SmtQuery::new("q1", "(check-sat)");
        let pb_report = PbSmtReport {
            query_id: query.query_id.clone(),
            query_hash: query.query_hash(),
            status: SmtStatusCode::SmtStatusUnknown as i32,
            solver_identity: None,
            model: None,
            unsat_core: None,
            diagnostics: None,
            wall_time_seconds: 0.0,
        };

        let report = map_report(&query, pb_report);

        assert_eq!(report.execution_identity.backend, "remote-cvc5");
        assert!(report.execution_identity.native_identity.is_none());
    }
}
